apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: tf-controller
  namespace: tf-controller
spec:
  interval: 5m
  chart:
    spec:
      chart: tf-controller
      version: "^0.10.0"
      sourceRef:
        kind: HelmRepository
        name: tf-controller
        namespace: tf-controller
      interval: 1m
